/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ufo.glb --debug 
Author: BlackHawk0512 (https://sketchfab.com/BlackHawk0512)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/ufo-flying-saucer-spaceship-ovni-094ce2baf6ee40aa8f083b7d0fcf0a9f
Title: UFO Flying Saucer Spaceship OVNI
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ufo.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.UFO_Ventanilla_0.geometry} material={materials.Ventanilla} />
        <mesh geometry={nodes.UFO_UFO_Metal_0.geometry} material={materials.UFO_Metal} />
        <mesh geometry={nodes.UFO_UFO_Metal_0_1.geometry} material={materials.UFO_Metal} />
        <mesh geometry={nodes.UFO_UFO_Metal_0_2.geometry} material={materials.UFO_Metal} />
        <mesh geometry={nodes.UFO_UFO_BLACK_0.geometry} material={materials.UFO_BLACK} />
      </group>
    </group>
  )
}

useGLTF.preload('/ufo.glb')
